### ISSUE TITLE
Sorry about this

### ISSUE THREAD

**Issue by oddbookworm** [yunline/yunline.github.io#4]
I'm sorry for contacting you this way, but I felt like it was better than grabbing your email from your commits and emailing you out of the blue. I reviewed one of your pull requests on pygame for context about who I am. I want to reach out and talk to you privately. Would that be something you'd be amenable to?

**Comment by yunline** [comment]
> I'm sorry for contacting you this way, but I felt like it was better than grabbing your email from your commits and emailing you out of the blue. I reviewed one of your pull requests on pygame for context about who I am. I want to reach out and talk to you privately. Would that be something you'd be amenable to?

Sure.  √

**Comment by oddbookworm** [comment]
Are email or discord options for you?

**Comment by yunline** [comment]
> Are email or discord options for you?

Email is ok. Discord is not available in China.

**Comment by oddbookworm** [comment]
Thank you, please email me at oddbookworm1@outlook.com
